
services:
  db:
    image: mysql:latest
    container_name: sms_database
    environment:
      - MYSQL_USER=sms_user
      - MYSQL_PASSWORD=Password123
      - MYSQL_DATABASE=sms_db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  backend_api:
    build: ./backend_api
    container_name: sms_backend_api
    environment:
      - DB_HOST=db
      - DB_USER=sms_user
      - DB_PASSWORD=Password123
      - DB_NAME=sms_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  worker:
    build: ./worker
    container_name: sms_worker
    environment:
      - DB_HOST=db
      - DB_USER=sms_user
      - DB_PASSWORD=Password123
      - DB_NAME=sms_db
      - SMS_GATEWAY_IP=192.168.1.63
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: